version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: docker/build/php/Dockerfile
        ports:
            - "8060:8060"
        volumes:
            - .:/var/www/mars:z  
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - ./docker/build/php/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

     # Configure the database
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}