version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: docker/build/php/Dockerfile
        ports:
            - "8060:8060"
        volumes:
            - .:/var/www/billie:z  
     # Configure the database
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}